### ISSUE TITLE
Error "File exists: '/opt/activemq/conf.tmp'" when using docker-compose

### ISSUE THREAD

**Issue by chrned** [disaster37/activemq#9]
Hi. We are using 5.11.1 in a docker-compose setup. 
This seems to trigger some kind of race condition.
Initial startup is always succesful while following starts often (but not always) fails like this:

``` bash
2015-08-14 14:25:14,309 CRIT Supervisor running as root (no user in config file)
2015-08-14 14:25:14,311 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2015-08-14 14:25:14,311 WARN Included extra file "/etc/supervisor/conf.d/activemq.conf" during parsing
2015-08-14 14:25:14,323 INFO RPC interface 'supervisor' initialized
2015-08-14 14:25:14,325 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2015-08-14 14:25:14,325 INFO supervisord started with pid 15
2015-08-14 14:25:15,327 INFO spawned: 'cron' with pid 18
2015-08-14 14:25:15,328 INFO spawned: 'activemq' with pid 19
2015-08-14 14:25:16,418 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-08-14 14:25:16,418 INFO success: activemq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/init.py", line 366, in <module>
    shutil.copytree(ACTIVEMQ_HOME + "/conf/", ACTIVEMQ_CONF);
  File "/usr/lib/python2.7/shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/opt/activemq/conf.tmp'
Traceback (most recent call last):
  File "/app/init.py", line 366, in <module>
    shutil.copytree(ACTIVEMQ_HOME + "/conf/", ACTIVEMQ_CONF);
  File "/usr/lib/python2.7/shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/opt/activemq/conf.tmp'
Traceback (most recent call last):
  File "/app/init.py", line 366, in <module>
    shutil.copytree(ACTIVEMQ_HOME + "/conf/", ACTIVEMQ_CONF);
  File "/usr/lib/python2.7/shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/opt/activemq/conf.tmp'
```

Do you have any idea why this is happening?

**Comment by burner1024** [comment]
I'm having the same issue, and I think it started after I've added user/password environment variables to compose file.

**Comment by disaster37** [comment]
Hum, maybee when you start and stop container with docker-compose, it's doesn't destroy it at the send. So the second time you start it, all temporary folder already exist (aka /opt/activemq/conf.tmp).

I think if you use docker-compose start and stop the container is not destroyed (it's the same). But if you use docker-compose stop and docker-compose up -d, it destroy container each time.

Il all case, I will patch the init script to clean folder /opt/activemq/conf.tmp before copying ;)

**Comment by chrned** [comment]
This solved my problem. Thanks for the quick response. 

The problem was actually also present with docker-compose up -d since it reuses the container unless the image has been updated since the container was created.

**Comment by disaster37** [comment]
You have right. Before, when docker-compose was fig, it recreate container each time.But now, with docker compose, you must use "docker compose up --force-recreate -d" to do that ;)
.Date: Wed, 19 Aug 2015 14:14:17 -0700

**Comment by disaster37** [comment]
Ok so I have inserted a pull request that already fix the problem (clean temporary conf folder before move the conf on it). The docker image webcenter/activemq:latest and webcenter/activemq:5.11.1 are rebuilded.

So stop and destroy your container, destroy image and try again ;)
